[package]
name = "overflow"
version = "0.1.0"
edition = "2021"

[profile.dev]
overflow-checks = false     # Disable integer overflow checks.

# Optional: You can add [profile.test] if you want similar behavior during testing
[profile.test]
overflow-checks = false